// <auto-generated />
namespace ManagerHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddData));
        
        string IMigrationMetadata.Id
        {
            get { return "202304221543011_Add Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
